name: cytospace
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - numpy=1.22.2
  - lap=0.4.0
  - scipy=1.8.0
  - pip=22.0.4
  - pandas=1.4.1
  - matplotlib=3.5.1
  - r-seurat=3.2.3
  - r-spatstat=1.64-1
  - bioconductor-glmgampoi=1.2.0
  - gdown=4.4.0
  - r-argparse=2.1.6
  - pip:
    - ortools==9.2.9972
    - scanpy==1.9.3
    - datatable==0.11.1
